### ISSUE TITLE
Minta tolong kerja manual

### ISSUE THREAD

**Issue by fakhrullah** [fakhrullah/moscdotmy#1]
Ade beberapa perkara yang perlukan kerja manual, jadi minta tolong sikit, sape2 yang free.

Untuk elakkan ramai orang buat satu kerja yang sama. Kalau ada benda yang nak buat, 

1. tinggalkan komen di bawah
2. Buka isu baru dengan tajuk yang sesuai. Contoh: "Edit content/malaysia-open-source-conference-2017-moscmy-2017.md"
3. Sebab ini kerja mudah tapi perlukan kerajinan, sila selesaikan dalam tempoh kurang 3 hari. 

## Todo

1. Sesetengah boleh ditulis dengan format lebih baik. Bold, italic dan heading (h2, h3, ...) yang mana perlu. Links pun kna betulkan ke internal link mana yang perlu.
2. Download gambar-gambar dalam contents ke dalam `static/images/` directory kemudian edit artikel berkenaan link kan gambar dengan internal `/images/nama-fail-gambar.png`. Jangan lupa rename gambar dengan nama yang senang baca dan boleh faham untuk tujuan SEO.
3. Copy writing. Contoh, description tentang web, dekat sidebar kiri tu panjang sangat, sape boleh edit jadikan kurang 150 aksara. Dalam `config.yaml` bawah `params` variable, `description` label.

## Workflow

Guna github workflow. Branch dari master.

Sape yang tak pandai git, tapi nak tolong jugak. Boleh buka issue dan tulis je dalam tu. Sebab artikel sedia ada tak panjang sangat jadi guna issue pun ok kot. Kemudian, sesape yang pandai git (termasuk me), tolong sambung kerja mereka please. 

## Cara nak start run website

1. Install Hugo.
2. Clone projek.
3. Install theme dulu. Sebab theme tak confirm lagi, theme Musang yang digunakan dekat demo tak push ke dalam repo lagi.
4. Pastu run `hugo server` untuk test tengok website.
  *tips tambahan*: `hugo server --renderToDisk` utk laptop2 yang xcukup RAM.

**updated**: baru perasan ayat tak lengkap, tulis nk cepat, gini lah jadinya.

**Comment by amirulabu** [comment]
saya sedang edit registration. tambah link ke ticket2u. tak boleh run server
```
$ hugo server

Error: Unable to find theme Directory: /home/ruler/workspace/moscdotmy/themes/musang
```
edit: problem setel. kena clone theme musang dulu
``` 
git clone https://github.com/fakhrullah/musang.git
```

**Comment by fakhrullah** [comment]
aku ambik workshop-11, edit content, tulis elok2 dan dan rename file.

Updated: SETEL

**Comment by fakhrullah** [comment]
Semua setel dah, tapi mungkin ada yang terlepas pandang. Kalau jumpa, edit lah anytyme je. Thanks @amirulabu sebab banyak tolong bhgian ni.
