### ISSUE TITLE
Top sidebar hidden

### ISSUE THREAD

**Issue by k4ml** [fakhrullah/moscdotmy#11]
![screen shot 2017-04-09 at 7 04 37 pm](https://cloud.githubusercontent.com/assets/116353/24836777/9f418d16-1d57-11e7-8c31-18732228f95f.png)

Mungkin css issue.

**Comment by fakhrullah** [comment]
2 issue ni, satu description panjang sangat and font besar sangat.

Yang ni sebab berkaitan dengan theme, jadi saya setelkan.

**Comment by fakhrullah** [comment]
@k4ml berapa lama baru github page tu update yang baru? Macam lambat sangat je update, lepas push gh-pages, website tak sama dengan file dalam gh-pages.

**Comment by fakhrullah** [comment]
![moscmy-sidebar-image](https://cloud.githubusercontent.com/assets/5182052/24906503/88e7eaa8-1eea-11e7-9a0a-e695b9cc6524.png)

Saje nk menunjuk, them tak edit lagi.

**Comment by fakhrullah** [comment]
https://github.com/fakhrullah/moscdotmy/pull/14

**Comment by fakhrullah** [comment]
#14

**Comment by fakhrullah** [comment]
Setel lepas update theme.
