### ISSUE TITLE
Guna gh-pages untuk web

### ISSUE THREAD

**Issue by fakhrullah** [fakhrullah/moscdotmy#3]
Sekarang, web di generate dekat `docs/`, repo jadi macam serabut dan besar. Jadi, klu boleh wat gh-pages, tak serabut sangat kot.

rujukan: https://gohugo.io/tutorials/github-pages-blog/

**Comment by k4ml** [comment]
I'll take this.

**Comment by fakhrullah** [comment]
ok. tq
